In [1]:
import numpy as np
import matplotlib.pyplot as plt
from utils import *

%matplotlib inline


In [2]:
X = np.array([10, 20, 30, 40, 50])
Y = np.array([-1, -1, -1, -1, -1])
X*Y


array([-10, -20, -30, -40, -50])

In [3]:
Y/2

array([-0.5, -0.5, -0.5, -0.5, -0.5])

In [4]:
X

array([10, 20, 30, 40, 50])

In [5]:
X.shape

(5,)

In [7]:
for i in enumerate(X): 
    print( i )

(0, np.int64(10))
(1, np.int64(20))
(2, np.int64(30))
(3, np.int64(40))
(4, np.int64(50))


In [8]:
X = np.array([
    [10, 2, 5, 4],
    [5, 26, 7, 8],
    [19, 1, 15, 6]
])
np.mean(X, axis=0)

array([5., 6., 7., 8.])

In [9]:
means=np.mean(X, axis=0)
var = np.sum( (X-means)**2 )
print(var)


128.0


In [10]:
(X-means)**2


array([[16., 16., 16., 16.],
       [ 0.,  0.,  0.,  0.],
       [16., 16., 16., 16.]])

In [11]:
means

array([5., 6., 7., 8.])

In [13]:
V=np.zeros(X.shape[1])
for i, x in enumerate(X): 
    V = V + (x-meanXs)**2
V = V/X.shape[1]
V

array([8., 8., 8., 8.])

In [14]:
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
X.shape[1]

4

In [16]:
X.shape[0]

3

In [38]:
V=np.zeros(X.shape[1], dtype='float32')
for j in range(X.shape[1]):
    for x in X[:, j]:
        print(f"{x},{means[j]}, {(x-means[j])**2}")
        V[j] += (x-means[j])**2
    V[j] = V[j]/V.shape[0]

V


1,5.0, 16.0
5,5.0, 0.0
9,5.0, 16.0
2,6.0, 16.0
6,6.0, 0.0
10,6.0, 16.0
3,7.0, 16.0
7,7.0, 0.0
11,7.0, 16.0
4,8.0, 16.0
8,8.0, 0.0
12,8.0, 16.0


array([8., 8., 8., 8.], dtype=float32)

In [43]:
X = np.array([
    [10, 2, 5, 41],
    [5, 26, 27, 18],
    [19, 1, 15, 6]
])
np.mean(X, axis=0)

array([11.33333333,  9.66666667, 15.66666667, 21.66666667])

In [44]:
means = np.mean(X, axis=0)

V=np.zeros(X.shape[1], dtype='float32')
for j in range(X.shape[1]):
    print(f">>{j}")
    for x in X[:, j]:
        print(f"steps {x},{means[j]}, {(x-means[j])**2}")
        V[j] += (x-means[j])**2
        
    V[j] = V[j]/V.shape[0]
V

>>0
steps 10,11.333333333333334, 1.7777777777777795
steps 5,11.333333333333334, 40.11111111111112
steps 19,11.333333333333334, 58.77777777777777
>>1
steps 2,9.666666666666666, 58.77777777777777
steps 26,9.666666666666666, 266.7777777777778
steps 1,9.666666666666666, 75.1111111111111
>>2
steps 5,15.666666666666666, 113.77777777777777
steps 27,15.666666666666666, 128.44444444444446
steps 15,15.666666666666666, 0.44444444444444364
>>3
steps 41,21.666666666666668, 373.7777777777777
steps 18,21.666666666666668, 13.444444444444454
steps 6,21.666666666666668, 245.44444444444449


array([ 25.166666, 100.166664,  60.666668, 158.16667 ], dtype=float32)